name: Continuous Deployment
on:
  push: 
    tags:
    - 2*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
    - name: Unshallow
      run: git fetch --prune --unshallow

    # Caches and restores the bazel build directory.
    - name: Cache bazel build results
      uses: actions/cache@v2.0.0
      env:
        cache-name: bazel-cache
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-master

    - name: Publish containers
      run: /bin/bash -c "tools/publish.sh"
      env:
        GCR_BITNAMI_LABS: ${{ secrets.GCR_BITNAMI_LABS }}

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x

    - name: Publish release
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
