name: Continuous Integration
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  check:
    name: Check Integration
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build targets
      uses: docker://l.gcr.io/google/bazel:4.0.0
      with:
        entrypoint: /bin/bash
        args: bazel build //...
    - name: Test targets
      uses: docker://l.gcr.io/google/bazel:4.0.0
      with:
        entrypoint: /bin/bash
        args: bazel test //...
