name: Continuous Deployment
on:
  push: 
    tags:
    - 2*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Unshallow
      run: git fetch --prune --unshallow
    - name: Publish containers
      uses: docker://l.gcr.io/google/bazel:4.0.0
      with:
        entrypoint: /bin/bash
        args: -c "tools/publish.sh"
      env:
        GCR_BITNAMI_LABS: ${{ secrets.GCR_BITNAMI_LABS }}
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: Publish release
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
