name: Continuous Integration
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  check:
    name: Check Integration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Caches and restores the bazel build directory.
    - name: Cache bazel build results
      uses: actions/cache@v2.0.0
      env:
        cache-name: bazel-cache
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-master

    - name: Build targets
      with:
        entrypoint: /bin/bash
        args: bazel build //...

    - name: Test targets
      with:
        entrypoint: /bin/bash
        args: bazel test //...
